//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
    using System;
    using StudentCourses.Domain.Interfaces;
    using System.Collections.Generic;

namespace StudentCourses.Infrastructure.EntityModel
{
    
    public partial class CourseEntityModel : IEntityModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CourseEntityModel()
        {
            this.Registrations = new HashSet<RegistrationEntityModel>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int Vacancies { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistrationEntityModel> Registrations { get; set; }
    }
}
