//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentCourses.Infrastructure.EntityModel
{
    using System;
    using System.Collections.Generic;
    using StudentCourses.Domain.Interfaces;
    
    public partial class RegistrationEntityModel : IEntityModel
    {
        public int ID { get; set; }
        public int Student_ID { get; set; }
        public int Course_ID { get; set; }
        public string RegistrationKey { get; set; }
    
        public virtual CourseEntityModel Course { get; set; }
        public virtual StudentEntityModel Student { get; set; }
    }
}
